### PR TITLE
Fixed Guzzle package name.

### PR DESCRIPTION
**Pull request by corpsee**
Fixed Guzzle package name ('guzzle/guzzle' -> 'guzzlehttp/guzzle'). Issue #4.

### CODE REVIEW

**Review by mremi — COMMENTED** [review]
Thx @corpsee , can you add a `CHANGELOG.md` with this update please?
```markdown
CHANGELOG
=========

master
------

* Replace guzzle/guzzle by guzzlehttp/guzzle
```

**Comment by corpsee** [comment]
@mremi  Done.

**Comment by mremi** [comment]
Thx @corpsee I'll merge this one after the fix of CI in #5

**Comment by mremi** [comment]
Can you rebase please?

**Comment by corpsee** [comment]
@mremi Done.

**Comment by mremi** [comment]
Thx 👍

**Pull request merged**
