### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mremi** [comment]
Hi,

Your PR has broken the CI.
Why do you want to replace `symfony/console` by `symfony/yaml`?

**Comment by mremi** [comment]
@OxGroup ?

**Comment by ghost** [comment]
To support the latest developments in test tools you need to update all versions. I see that there is a dependence on other modules, but it still needs to do

**Comment by mremi** [comment]
Upgrade can be done, but `symfony/console` is required

**Comment by mremi** [comment]
@OxGroup Any news please?

**Pull request closed without merging**
